apiVersion: 1

datasources:
  - name: StockDB
    type: grafana-postgresql-datasource
    access: proxy
    url: postgres:5432
    database: stockdb
    user: stock
    secureJsonData:
      password: stockpass
    jsonData:
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false
    isDefault: true
    editable: false
